spring:
  application:
    name: e-com
server:
  port: 8080
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecom
razorpay:
  key: rzp_test_S6559zCerrUAAq
  secret:  aB7AAQ1FnBqdKwJe346XzrO5
